### ISSUE TITLE
Colors are very very different

### ISSUE THREAD

**Issue by samrathchadha** [arcticlimer/djanho#1]

**Comment by viniciusmuller** [comment]
Hi, could you elaborate a bit more? As vscode themes are pretty irregular, most of the themes lack some of the highlighting groups, djanho will try to fallback those missing groups to other existing groups, but some themes might have so few defined color tokens that there is a difference. Also some themes have a string of groups separated by commas at their tokenColors fields, djanho currently doesn't handle those correctly.
