### ISSUE TITLE
Fails to convert: red-evil-theme

### ISSUE THREAD

**Issue by Dimfred** [arcticlimer/djanho#2]
Hi man nice idea. 
I am currently trying to convert:
https://github.com/flumiie/vscode-evil-red-theme

any chance you could check why it is no working? In the other issue I read somethingabout the `colorToken` that it is not handled correctly, it is currently in this theme so maybe thats why.

**Comment by viniciusmuller** [comment]
https://github.com/flumiie/vscode-evil-red-theme/blob/49e3694e35d8de870bd8a2c07beb4c2c34f97b22/themes/.color-theme.json#L135

The theme imports a textMate configuration file (I didn't even knew those existed) and apparently VSCode handles it without any problem. Djanho can't really handle those, as a new parser would be needed for it.

**Comment by Dimfred** [comment]
Thx for checking it! That is sad, maybe I can convert it, or I'll just recreate the theme. Anyhow, thx :)
